import React, { useCallback, useMemo, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { useDispatch, useSelector } from 'react-redux'
import { IStateType } from '@redux-state/state'
import { increment } from '@features/example/example.action'
// or use this method for make it clear
import { exampleAction } from '@features/example'

import Typography from '@components/atoms/Typography'
import Footer from '@components/organisms/Footer'
import { NavbarNext } from '@components/molecules/Navbar'
import Button from '@components/atoms/Button'
import { Col, Grid, Row } from '@components/atoms/GridSystem'
import Container from '@components/atoms/Container'
import { searchProductNetwork } from '@network/catalog/product'
import useSWR from 'swr'

function ExamplePage() {
  const count = useSelector((state: IStateType) => state.example.count)
  const dispatch = useDispatch()

  const [page, setPage] = useState(1)
  const [limit, setLimit] = useState(10)
  const [search, setSearch] = useState('')

  const PRODUCT_SWR_KEY = useMemo(
    () => `/product/?page=${page}&limit=${limit}}&search=${search}`,
    [page, limit, search]
  )
  const fetcher = useCallback(
    async () => await searchProductNetwork({ limit, page, search }),
    [page, limit, search]
  )
  const { data: productsResp, isValidating } = useSWR(PRODUCT_SWR_KEY, fetcher)

  const menu = [
    { child: 'Beranda', isActive: true, link: '/' },
    { child: 'Artikel', isActive: false, link: '' },
    { child: 'Catalog', isActive: false, link: '' },
    { child: 'Treatment', isActive: false, link: '' },
    { child: 'Klinik', isActive: false, link: '' },
    { child: 'Reseller', isActive: false, link: '' },
    { child: 'Tentang Kami', isActive: false, link: '' },
  ]

  return (
    <div>
      <Head>
        <title>Ella Dev Team</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <NavbarNext listMenu={menu} totalCartItem={21} totalNotifItem={10} /> */}
      <main>
        <Container>
          <h1>
            Welcome to <a href="https://nextjs.org">Ella</a>
          </h1>
          <p>
            Get started by editing <code>pages/*.tsx</code>
          </p>
          {count}
          <Button
            onClick={() => dispatch(increment())}
            isSmall={false}
            textVariant={16}
          >
            Tambah
          </Button>
          <hr />
          <Button onClick={() => dispatch(exampleAction.decrement())}>
            Kurang
          </Button>
          <Button
            onClick={() => {
              setPage(page + 1)
            }}
          >
            Mutate
          </Button>
          <>{!!productsResp && JSON.stringify(productsResp.data, null, 2)}</>
          <Grid debug>
            <Row>
              <Col xs={4} md={6} xl={5}>
                Col hallo
              </Col>
              <Col xs={4} md={6} lg={7}>
                Col hallo
              </Col>
              <Col xs={2} md={6} lg={12}>
                Col hallo
              </Col>
              <Col xs={2} md={6} xl={12}>
                Col
              </Col>
            </Row>
            <Row>
              <Col xs={2} md={6} xl={12}>
                Col
              </Col>
            </Row>
          </Grid>
          <Typography as={'p'}>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda
            quas illo molestiae a aliquam quo natus nihil. Tempore ad harum
            cupiditate consectetur numquam libero illum blanditiis maxime. Ea,
            repellat dicta! Harum aperiam voluptatem enim quidem temporibus
            beatae porro nam, et consequuntur ad magnam ut maxime delectus
            veritatis, illum quos sunt quas nemo distinctio, ea velit. Cumque ut
            consectetur eligendi animi. Laboriosam dignissimos dolores
            voluptates quaerat, iure aspernatur minima dicta accusamus tenetur
            deserunt sed perferendis aliquid nihil mollitia atque, repudiandae
            suscipit expedita cumque eos illo odio. Deserunt facere itaque
            voluptatum non. Accusamus rem officia corporis suscipit incidunt
            sapiente ipsa voluptate aspernatur illo ratione? Eum culpa est
            repellendus molestiae, dolore, cupiditate pariatur veniam officia
            eos fuga repellat dolorum necessitatibus nemo excepturi aut!
            Laboriosam voluptatum consequatur iste? Veniam, nisi dignissimos
            iure quae neque reiciendis porro. Quaerat atque suscipit consequatur
            ipsa dolor eius alias enim commodi ea. Voluptatem laboriosam
            repudiandae nisi sed delectus quaerat. Itaque inventore officiis est
            cum explicabo, optio qui molestiae ab voluptatum repudiandae eius
            doloremque similique, quam laudantium ut? Repudiandae explicabo
            harum, possimus similique libero repellendus est repellat sequi
            rerum? Dolores? Adipisci aut aliquid praesentium, sapiente nostrum
            ipsa voluptatem veniam? Sint neque repellat magnam sunt amet
            provident, placeat ea minus iure et ullam facere cupiditate rem,
            dolorem ipsa consectetur error molestias! Ratione quidem qui
            reiciendis odit. Voluptatem quos quisquam rerum praesentium dolore
            ea et laboriosam qui rem perspiciatis ducimus explicabo labore modi
            porro dolorem, nobis doloremque excepturi deserunt eum, voluptas
            impedit? Nesciunt ad ex nobis possimus mollitia autem nihil fugit,
            dolore aliquam adipisci itaque ab distinctio obcaecati et
            consequuntur hic ducimus iure consectetur, harum vel reiciendis
            perferendis nulla voluptatum. Maiores, tempora. Neque eligendi sunt,
            vero molestias assumenda esse reiciendis inventore doloribus
            consectetur unde quod harum repellat modi necessitatibus. Accusamus
            aperiam quae excepturi non tenetur officia velit expedita fugiat
            dicta rem. Quam? Autem itaque possimus illum asperiores consequuntur
            vitae sunt natus soluta nam quia? Saepe nisi sit alias laborum
            numquam dolores asperiores ea. Ab quod dolore delectus, omnis cumque
            vitae quibusdam ad. Est ipsa vero ratione officiis provident eveniet
            molestiae a magnam, fuga dolorem expedita sapiente animi! Vitae
            natus, similique eos iste error quas nostrum odio quo laboriosam,
            eum tempora asperiores non.
          </Typography>
        </Container>
      </main>

      <Footer variant={'grey'} imageAs={Image} />
    </div>
  )
}

export default ExamplePage
